title: "Kennidy L. Guimarães"
description: "Writer and Software Developer"
baseurl: "kennidy-l-guimaraes.github.io"
url: ""
lang: "en-us"

author:
  name: "Kennidy L. Guimarães"
  role: "Writer and software developer"
  github: "Kennidy-L-Guimaraes"
  instagram: "Kennidy.L.Guimaraes"
  twitter: "kennidyl.guimaraes"
  medium: "kennidylguimaraes"
  avatar: "/assets/img/HarpyFortofBrazil.png"
  email: "kennidylguimaraes@gmail.com"
  address: "Florianópolis, Brazil"

future: true
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-mermaid
  - jekyll-sass-converter
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js'

collections:
  softwares:
    output: true
    permalink: /softwares/:name/
  papers:
    output: true
    permalink: /papers/:name/
  articles:
    output: true
    permalink: /articles/:name/
  essays:
    output: true
    permalink: /essays/:name/