title: "Kennidy L. Guimarães"
description: "Writer and Software Developer"
baseurl: ""
url: "https://kennidy-l-guimaraes.github.io"
lang: "en-us"

author:
  name: "Kennidy L. Guimarães"
  role: "Writer and software developer"
  github: "Kennidy-L-Guimaraes"
  instagram: "Kennidy.L.Guimaraes"
  twitter: "kennidyl.guimaraes"
  medium: "kennidylguimaraes"
  avatar: "/assets/img/HarpyFortofBrazil.png"
  email: "kennidylguimaraes@gmail.com"
  address: "Florianópolis, Brazil"

future: true
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-mermaid
  - jekyll-sass-converter
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js'

collections:
  softwares:
    output: true
    permalink: /softwares/:name/
  papers:
    output: true
    permalink: /papers/:name/
  articles:
    output: true
    permalink: /articles/:name/
  essays:
    output: true
    permalink: /essays/:name/

announcement:
  active: true
  show_on: all          # "home" ou "all" (todas as páginas)
  label: "Important!"    # texto do badge vermelho
  message: "Please note that this website is still under construction; it may undergo changes, present inconsistencies, and its articles may be redirected. Thank you for your understanding."
  cta_text: "Get in touch"
  cta_url: " "